from dataclasses import dataclass
from typing import List, Optional, Union
from numpy.typing import ArrayLike, NDArray
import pickle


class Slope2NoiseUnpickler(pickle.Unpickler):
    """Custom unpickler for serialised object generated by slope2noise"""

    def find_class(self, module, name: str):
        """Find the correct class in the submodule given a module name"""
        if module == "slope2noise.rooms":
            # Adjust the module path here if needed
            module = "slope2noise.dataclass"
        return super().find_class(module, name)


@dataclass
class CommonSlopesRIR():
    ''' 
    dataclass for the synthesized RIRs using shaped wgn and common slope parameters
    '''
    room_dims: List
    room_start_coords: List
    source_locs: Union[ArrayLike, NDArray]
    receiver_locs: NDArray
    n_slopes: int
    a_vals: NDArray
    t_vals: NDArray
    rir: NDArray
    sample_rate: float
    aperture_coords: Optional[List] = None
    batch_id: Optional[int] = None
    f_bands: Optional[ArrayLike] = None


@dataclass
class CommonSlopesRIRSimple():
    ''' 
    dataclass for the synthesized RIRs using shaped wgn and common slope parameters
    '''
    n_slopes: int
    a_vals: NDArray
    t_vals: NDArray
    rir: NDArray
    sample_rate: float
    batch_id: Optional[int] = None
    f_bands: Optional[ArrayLike] = None