n_rirs: 100
batch_size: 10
n_slopes: 2
ir_len: 96000
synthesis_type: "wgn"
t_vals: [0.5, 1.7]
room_geom_config:
  num_rooms: 2
  room_dims: [[4,8,2], [6,2,2]]
  start_coordinates: [[0,0,0], [4,2,0]]
  source_pos: [1, 0.5, 1.5]
amp_gen_config:
  generate_amplitude_based_on_geometry: True
  amp_dist_filepath: "../../resources/Georg_3room_FDTD/amplitude_distribution.pkl"

